[platformio]
extra_configs = platformio.ini

[env:Unified_ESP32_2400_RX_via_UART]
board_config = radiomaster.rx_2400.er6

; Existing ESP8285 receiver used for unsupported-platform regression builds.
[env:Unified_ESP8285_2400_RX_via_UART]
board_config = happymodel.rx_2400.epw6
